# Generated by Django 4.2.21 on 2025-05-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="description",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
